*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:43:24 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 043000cf68df
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaaade841cd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 1)
Python auto-reloader enabled
--- no python application found, check your startup logs for errors ---
[pid: 9|app: -1|req: -1/1] 172.24.0.1 () {54 vars in 1217 bytes} [Mon Jul  5 10:43:51 2021] GET / => generated 21 bytes in 9 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9|app: -1|req: -1/2] 172.24.0.1 () {56 vars in 1248 bytes} [Mon Jul  5 10:44:50 2021] GET / => generated 21 bytes in 8 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9|app: -1|req: -1/3] 172.24.0.1 () {56 vars in 1248 bytes} [Mon Jul  5 10:44:51 2021] GET / => generated 21 bytes in 4 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /code
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:8001)
running /usr/local/bin/uwsgi
*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:44:55 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 043000cf68df
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaaae37d7c40
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaae37d7c40 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 12, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:45:26 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 6d5c0e0ff742
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaaaed2cbcd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaaed2cbcd0 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
Python auto-reloader enabled
[pid: 8|app: 0|req: 1/1] 172.24.0.1 () {56 vars in 1248 bytes} [Mon Jul  5 10:45:42 2021] GET / => generated 16348 bytes in 92 msecs (HTTP/1.1 200) 3 headers in 96 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 2/2] 172.24.0.1 () {56 vars in 1248 bytes} [Mon Jul  5 10:46:22 2021] GET / => generated 16348 bytes in 17 msecs (HTTP/1.1 200) 3 headers in 96 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 3/3] 172.24.0.1 () {54 vars in 1227 bytes} [Mon Jul  5 10:46:27 2021] GET /admin => generated 0 bytes in 12 msecs (HTTP/1.1 301) 3 headers in 112 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 4/4] 172.24.0.1 () {54 vars in 1229 bytes} [Mon Jul  5 10:46:27 2021] GET /admin/ => generated 0 bytes in 31 msecs (HTTP/1.1 302) 7 headers in 265 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 5/5] 172.24.0.1 () {54 vars in 1266 bytes} [Mon Jul  5 10:46:27 2021] GET /admin/login/?next=/admin/ => generated 1855 bytes in 47 msecs (HTTP/1.1 200) 7 headers in 381 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 6/6] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:46:33 2021] GET / => generated 16348 bytes in 24 msecs (HTTP/1.1 200) 3 headers in 96 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 7/7] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:47:43 2021] GET / => generated 16348 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 96 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 8/8] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:47:45 2021] GET / => generated 16348 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 96 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./app/urls.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 8)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /code
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:8001)
running /usr/local/bin/uwsgi
*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:48:57 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 6d5c0e0ff742
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaaae2bbbd10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaaae2bbbd10 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 11, cores: 1)
Python auto-reloader enabled
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app/urls.py", line 21, in <module>
    path('', include("monk.urls"))
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./monk/urls.py", line 6, in <module>
    path("",views.index,name="home")
AttributeError: module 'monk.views' has no attribute 'index'
[pid: 11|app: 0|req: 1/1] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:50:14 2021] GET / => generated 135845 bytes in 180 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./app/settings.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 11)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /code
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:8001)
running /usr/local/bin/uwsgi
*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:50:39 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 6d5c0e0ff742
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaaaf53fcd10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xaaaaf53fcd10 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 14, cores: 1)
Python auto-reloader enabled
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app/urls.py", line 21, in <module>
    path('', include("monk.urls"))
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./monk/urls.py", line 6, in <module>
    path("",views.index,name="home")
AttributeError: module 'monk.views' has no attribute 'index'
[pid: 14|app: 0|req: 1/1] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:50:40 2021] GET / => generated 135890 bytes in 118 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file ./monk/views.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 14)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /code
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:8001)
running /usr/local/bin/uwsgi
*** Starting uWSGI 2.0.17 (64bit) on [Mon Jul  5 10:52:07 2021] ***
compiled with version: 8.3.0 on 05 July 2021 10:43:07
os: Linux-5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
nodename: 6d5c0e0ff742
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.14 (default, Jun 29 2021, 21:09:03)  [GCC 8.3.0]
Python main interpreter initialized at 0xaaab0133dd10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaaab0133dd10 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 17, cores: 1)
Python auto-reloader enabled
[pid: 17|app: 0|req: 1/1] 172.24.0.1 () {56 vars in 1324 bytes} [Mon Jul  5 10:52:08 2021] GET / => generated 20 bytes in 29 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
